spring:
  config:
    activate:
      on-profile: dev

# Для разработки используем PLAINTEXT и эмулятор
audit:
  enabled: true
  develop-mode: true
  fill-error: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:omni1-emulator-kafka:9092}
    security:
      protocol: PLAINTEXT
    ssl:
      key-store-location: ""
      key-store-type: ""
      key-store-password: ""
      trust-store-location: ""
      trust-store-type: ""
      trust-store-password: ""
      key-password: ""
    producer:
      properties:
        max.block.ms: 30000
        default.api.timeout.ms: 30000
        request.timeout.ms: 30000
        delivery.timeout.ms: 60000
        retries: 10
        retry.backoff.ms: 1000
        slider.wait.ms: 5000
    properties:
      slider.enable: true

  standin-kafka:
    enabled: false

  default-resolver:
    sub: "emulator"
    channel: "emulator"

  in-memory-skipped-storage:
    enabled: true
    resend-cron: "0 */10 * * * *"
    delay-force-send: 300

  circular-buffer:
    enabled: true
    capacity: 10000

  health:
    kafka:
      enabled: true

audit-events:
  block-settings:
    SUMD_MRMSCREATEMODEL: false
    SUMD_MRMSREMOVEMODEL: false
    SUMD_MRMSUPLOADREPORT: false
    SUMD_AUTH: false

logging:
  level:
    ru.vtb.omni.audit: DEBUG
    ru.vtb.auditproxy: DEBUG
    org.apache.kafka: DEBUG