spring:
  application:
    name: audit-proxy-prod

ms:
  properties:
    info-system-code: "SUM_BACKEND"
    info-system-id: "1661"

audit:
  kafka:
    bootstrap-servers: kafka-cluster-prod:9092
  standin-kafka:
    enabled: true
    bootstrap-servers: kafka-cluster-standin:9092