spring:
  application:
    name: audit-proxy

server:
  port: 8081

ms:
  properties:
    info-system-code: "SUM_BACKEND"
    info-system-id: "1661"
    appName: ${spring.application.name}

audit:
  enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topic: audit-v2
    security:
      protocol: SSL
    ssl:
      key-store-location: ${KAFKA_KEYSTORE_LOCATION:file:/etc/certificate/kafka-keystore.jks}
      key-store-type: JKS
      key-store-password: ${KAFKA_KEYSTORE_PASSWORD}
      trust-store-location: ${KAFKA_TRUSTSTORE_LOCATION:file:/etc/certificate/kafka-truststore.jks}
      trust-store-type: JKS
      trust-store-password: ${KAFKA_TRUSTSTORE_PASSWORD}
      key-password: ${KAFKA_KEY_PASSWORD}
    producer:
      properties:
        max.block.ms: 10000
        default.api.timeout.ms: 10000
        request.timeout.ms: 10000
        slider.wait.ms: 5000
    properties:
      slider.enable: true

  standin-kafka:
    enabled: ${STANDIN_KAFKA_ENABLED:false}
    bootstrap-servers: ${STANDIN_KAFKA_BOOTSTRAP_SERVERS:}
    security:
      protocol: SSL
    ssl:
      key-store-location: ${STANDIN_KAFKA_KEYSTORE_LOCATION:}
      key-store-type: JKS
      key-store-password: ${STANDIN_KAFKA_KEYSTORE_PASSWORD:}
      trust-store-location: ${STANDIN_KAFKA_TRUSTSTORE_LOCATION:}
      trust-store-type: JKS
      trust-store-password: ${STANDIN_KAFKA_TRUSTSTORE_PASSWORD:}
      key-password: ${STANDIN_KAFKA_KEY_PASSWORD:}
    producer:
      properties:
        max.block.ms: 10000
        default.api.timeout.ms: 10000
        request.timeout.ms: 10000
        slider.wait.ms: 5000
    properties:
      slider.enable: true

  blocking:
    blocking-skip-time: 300000
  all-block: false

  in-memory-skipped-storage:
    enabled: true
    resend-cron: "0 */10 * * * *"
    delay-force-send: 300

  circular-buffer:
    enabled: true
    capacity: 10000

  deployment-context:
    pod-name-environment: AUDITOMNI_POD_NAME
    pod-namespace-environment: AUDITOMNI_POD_NAMESPACE

  default-resolver:
    sub: "unknown"
    channel: "unknown"

  develop-mode: false

  health:
    kafka:
      enabled: true

audit-events:
  auditEventCodeList:
    - event-code: "SUMD_CREATEMODEL"
      schema: "vtb"
      auditEventGeneral:
        event_type: "Создание модели СУМ"
        object_type: "Модель"
        object_status: "CREATE"
        oper_name: "Запрос на создание модели в СУМ"
      auditEventStart:
        oper_description: "Начало создания модели"
      auditEventSuccess:
        oper_description: "Модель успешно создана"
      auditEventFailure:
        oper_description: "Ошибка создания модели"

    - event-code: "SUMD_REMOVEMODEL"
      schema: "vtb"
      auditEventGeneral:
        event_type: "Перевод в Архив"
        object_type: "Модель"
        object_status: "Remove"
        oper_name: "Запрос на перевод модели в статус Архив"
      auditEventStart:
        oper_description: "Начало перевода модели в архив"
      auditEventSuccess:
        oper_description: "Модель переведена в архив"
      auditEventFailure:
        oper_description: "Ошибка перевода модели в архив"

    - event-code: "SUMD_CANCELMODEL"
      schema: "vtb"
      auditEventGeneral:
        event_type: "Отмена разработки"
        object_type: "Модель"
        object_status: "Cancel"
        oper_name: "Запрос на отмену разработки модели"
      auditEventStart:
        oper_description: "Начало отмены разработки модели"
      auditEventSuccess:
        oper_description: "Разработка модели отменена"
      auditEventFailure:
        oper_description: "Ошибка отмены разработки модели"

    - event-code: "SUMD_UPLOADREPORT"
      schema: "vtb"
      auditEventGeneral:
        event_type: "Выгрузка отчета"
        object_type: "Модель"
        object_status: "Upload"
        oper_name: "Запрос на выгрузку отчета в СУМ"
      auditEventStart:
        oper_description: "Начало выгрузки отчета"
      auditEventSuccess:
        oper_description: "Отчет успешно выгружен"
      auditEventFailure:
        oper_description: "Ошибка выгрузки отчета"

    - event-code: "SUMD_TASKCOMPLETE"
      schema: "vtb"
      auditEventGeneral:
        event_type: "Закрытие задачи"
        object_type: "Модель"
        object_status: "Complete"
        oper_name: "Запрос на закрытие задачи"
      auditEventStart:
        oper_description: "Начало закрытия задачи"
      auditEventSuccess:
        oper_description: "Задача закрыта"
      auditEventFailure:
        oper_description: "Ошибка закрытия задачи"

    - event-code: "SUMD_ROLLBACKMODEL"
      schema: "vtb"
      auditEventGeneral:
        event_type: "Откат модели"
        object_type: "Модель"
        object_status: "Rollback"
        oper_name: "Запрос на откат модели"
      auditEventStart:
        oper_description: "Начало отката модели"
      auditEventSuccess:
        oper_description: "Модель откачена"
      auditEventFailure:
        oper_description: "Ошибка отката модели"

    - event-code: "SUMD_AUTH"
      schema: "auth_internal"
      auditEventGeneral:
        event_type: "Аутентификация"
        object_type: "Учетная запись"
        object_status: "AUTH"
        oper_name: "Запрос на аутентификацию пользователя"
      auditEventStart:
        oper_description: "Начало аутентификации"
      auditEventSuccess:
        oper_description: "Аутентификация успешна"
      auditEventFailure:
        oper_description: "Ошибка аутентификации"

  block-settings:
    SUMD_CREATEMODEL: false
    SUMD_REMOVEMODEL: false
    SUMD_CANCELMODEL: false
    SUMD_UPLOADREPORT: false
    SUMD_TASKCOMPLETE: false
    SUMD_ROLLBACKMODEL: false
    SUMD_AUTH: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-components: always
  health:
    defaults:
      enabled: false
    audit:
      kafka:
        enabled: true

logging:
  level:
    ru.vtb.omni.audit: DEBUG